name: "Core Plan"

#on:
#  push:
#    branches: [ACFTF34]
on:
  issue_comment:                                     
    types: [created, edited, deleted]
jobs:
  Core-Plan:
    #if: (github.event.comment.body == '/CORE_PLAN_PROD' || github.event.comment.body == '/CORE_PLAN_TEST')
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      pull-requests: write
      issues: write
      checks: read
      actions: write

    steps:
      - name: Set variables
        run: |
            acistate="Running"
            i=0
            while [ $acistate != "Terminated" ]
            do
              sleep 50
              echo $i
              i=$((i+1))
              if [[ $i -gt 5 ]]; then
                break
              fi
              acistate="Terminated"
            done
