name: "Core Plan"

#on:
#  push:
#    branches: [ACFTF34]
on:
  issue_comment:                                     
    types: [created, edited, deleted]
jobs:
  Core-Plan:
    #if: (github.event.comment.body == '/CORE_PLAN_PROD' || github.event.comment.body == '/CORE_PLAN_TEST')
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      pull-requests: write
      issues: write
      checks: read
      actions: write

    steps:
      - name: Set variables
        run: |
          echo ${{ github.event.issue.number }}
          echo ${{ github.event.comment.body  }}
          echo $GITHUB_REF_NAME
          echo ${{ github.sha }}
          echo "$(gh pr view $PR_NO --repo $REPO --json headRefName --jq '.headRefName')"
          REPO_NAME_SPLIT=`echo "$REPO" | awk -F '/' '{print $2}'`
          echo "REPO_NAME=$REPO_NAME_SPLIT" >> $GITHUB_ENV
        env:
          REPO: ${{ github.repository }}
          PR_NO: ${{ github.event.issue.number }}
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}

      - name: Print variables
        run: |
          echo $REPO_NAME